### ISSUE TITLE
CSS broken?

### ISSUE THREAD

**Issue by katieannemills** [remi-daigle/studyGroup#7]
not getting any CSS when I visit your page here: http://remi-daigle.github.io/studyGroup/ 

Let me know if I can help!

**Comment by dravery** [comment]
Hi Bill,
I think we sorted it. Yes?

trevor

**Comment by remi-daigle** [comment]
@BillMills yeah we had to do some tweaking of the website template to get it hosted at http://r-bar.ca

We used the SFU group's repository as a template since there was an issue with http vs https that we had trouble resolving and we knew the SFU group got their website hosted. The changes we made are mostly here: https://github.com/remi-daigle/studyGroup/commit/d2a2d1540f832fe5e0767d0a74b670e6698d5b11 and here: https://github.com/remi-daigle/studyGroup/commit/ea159fd9f1621d447ddaf58f8e9e93e40de1360d

Is there something "better" we should have done?

**Comment by katieannemills** [comment]
ahhh I see, you have a custom url - I was looking at remi-daigle.gihub.io/studyGroup - anyway, nope, this is perfect, well done!
